services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      app-network:
        aliases:
          - php.nginx.localhost

  php:
    build:
      context: .
      dockerfile: ./compose/php/Dockerfile
    scale: 3
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ./compose/php/php.ini:/usr/local/etc/php/php.ini
      - ./compose/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php-fpm:/var/log/php-fpm
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nginx_data: