services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ./compose/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./compose/logs/caddy:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      app-network:
        aliases:
          - php.caddy.localhost

  php:
    build:
      context: .
      dockerfile: ./compose/php/Dockerfile
    scale: 3
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ./compose/php/php.ini:/usr/local/etc/php/php.ini
      - ./compose/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./compose/logs/php-fpm:/var/log/php-fpm
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: